
version: '3.8'

services:

  # Backend service
  app-tier:
    build:
      context: ./application-code/app-tier
      dockerfile: Dockerfile
    container_name: app-tier
    environment:
      DB_HOST: ${DB_HOST}          # RDS endpoint
      DB_USER: ${DB_USER}          # RDS username
      DB_PASSWORD: ${DB_PASSWORD}  # RDS password
      DB_NAME: ${DB_NAME}          # RDS database name
      DB_PORT: ${DB_PORT}          # usually 3306
      PORT: 4000
    ports:
      - "4000:4000"
    restart: unless-stopped
    networks:
      - app-network

  # Frontend service
  web-tier:
    build:
      context: ./application-code/web-tier
      dockerfile: Dockerfile
    container_name: web-tier
    depends_on:
      - app-tier
    ports:
      - "80:80"
    environment:
      - REACT_APP_BACKEND_URL=http://44.201.12.97:4000
    restart: unless-stopped
    networks:
      - app-network

#  Custom network definition (not “default”)
networks:
  app-network:
    driver: bridge

